### ISSUE TITLE
NK model with capital example 

### ISSUE THREAD

**Issue by dypisgood** [chenwilliam77/RiskAdjustedLinearizations.jl#37]
Hi William,

Thanks for all the work, really appreciate it!

I read your model description for NK model with capital in the example folder, one thing that puzzles me is that on page 14 you write " _This system has three forward difference equations (25), (29), and (30)_".  Isn't equation (23), the Euler equation also forward looking? 

Best,
Yunpeng

**Comment by chenwilliam77** [comment]
The Euler equation is a forward looking equation, but I guess what is also special about those other equations is that there's a "dividend" and a "capital gains" term. I presume you could do the same with the Euler equation, but since it's pricing the risk free bond, I don't think there's a payoff to doing so. In the simple NK model example, I recall getting zero Euler equation errors in the risk free bond condition when simulating.

**Comment by dypisgood** [comment]
Thanks for the reply, sounds fair enough!

Just a follow-up question, consider a vanilla RBC model (CRRA preference, no friction at all), the Euler equation is the only forward-looking equation.  In this case does the number of strips matter?

**Comment by chenwilliam77** [comment]
It will depend on the specification of the shocks. If you have log-normal shocks, then you can exactly solve the model, and the risk-adjusted linearization would give you that result.
